apiVersion: apps/v1
kind: Deployment
metadata:
  name: discounts-deployment
  labels:
    app: discounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discounts
  template:
    metadata:
      labels:
        app: discounts
    spec:
      containers:
      - name: discounts
        image: moshootare/restauranty-discounts:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: restauranty-secrets
              key: MONGODB_URI
        - name: CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: restauranty-secrets
              key: CLOUD_NAME
        - name: CLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: restauranty-secrets
              key: CLOUD_API_KEY
        - name: CLOUD_API_SECRET
          valueFrom:
            secretKeyRef:
              name: restauranty-secrets
              key: CLOUD_API_SECRET
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: restauranty-secrets
              key: SECRET
        livenessProbe: null
        readinessProbe: null
