apiVersion: v1
kind: Service
metadata:
  name: discounts-service
spec:
  selector:
    app: discounts
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
