apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-deployment
  labels:
    app: items
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items
  template:
    metadata:
      labels:
        app: items
    spec:
      containers:
      - name: items
        image: moshootare/restauranty-items:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          value: "3003"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: restauranty-secrets
              key: MONGODB_URI
        - name: CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: restauranty-secrets
              key: CLOUD_NAME
        - name: CLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: restauranty-secrets
              key: CLOUD_API_KEY
        - name: CLOUD_API_SECRET
          valueFrom:
            secretKeyRef:
              name: restauranty-secrets
              key: CLOUD_API_SECRET
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: restauranty-secrets
              key: SECRET
        livenessProbe: null
        readinessProbe: null